package edu.ijse.absd.example.libmngsys.springmvc.model;

// Generated Sep 17, 2015 11:30:04 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "member", catalog = "libmngsysdb")
public class Member implements java.io.Serializable {

	private int id;
	private String name;
	private String address;
	private Set<Transaction> transactions = new HashSet<Transaction>(0);

	public Member() {
	}

	public Member(int id) {
		this.id = id;
	}

	public Member(int id, String name, String address,
			Set<Transaction> transactions) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.transactions = transactions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}

}
